### PR TITLE
Update DrOn from RxNorm_full_12042023

### PR DESCRIPTION
**Pull request by jamesaoverton**
This PR fills in terms from RxNorm that seemed to be missed by the previous code, using RxNorm_full_12042023.

### CODE REVIEW

**Comment by hoganwr** [comment]
I'm getting an error on this PR:

rm -f tmp/ldtab.db
java -jar tmp/ldtab.jar init tmp/ldtab.db --table dron_ingredient
java -jar tmp/ldtab.jar init tmp/ldtab.db --table dron_rxnorm
java -jar tmp/ldtab.jar init tmp/ldtab.db --table dron_ndc
java -jar tmp/ldtab.jar init tmp/ldtab.db --table dron_obsolete
java -jar tmp/ldtab.jar prefix tmp/ldtab.db ../scripts/prefix.tsv
sqlite3 tmp/ldtab.db < ../scripts/convert-dron-ldtab.sql
mkdir -p components
rm -f components/dron-ingredient.ttl
java -jar tmp/ldtab.jar export tmp/ldtab.db components/dron-ingredient.ttl --table dron_ingredient
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
robot --catalog catalog-v001.xml convert -i components/dron-ingredient.ttl -o components/dron-ingredient.owl
INVALID FORMAT ERROR unknown format: owl
For details see: http://robot.obolibrary.org/errors#invalid-format-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
make: *** [dron.Makefile:94: components/dron-ingredient.owl] Error 1

**Comment by jamesaoverton** [comment]
@hoganwr I saw the same error just now, and I can't explain it. Then I tried updating my ODK <https://oboacademy.github.io/obook/howto/odk-update/> and it seems to be working again. Can you please try running `docker pull obolibrary/odkfull` and then `sh run.sh make all_components -B` again?

**Comment by hoganwr** [comment]
Is not working. In fact I tried that on the one machine. I also tried on both machines stopping & restarting Docker (after updating odk) and then running sh run.sh make all_components -B again. Still get the error on both machines.

**Comment by hoganwr** [comment]
That fixed it on both machine (made sure it worked on the first machine before trying the second one).  Of course, update_repo "touches" a bunch of files, so now git status returns the following:

	modified:   ../../.github/workflows/qc.yml
	modified:   ../../docs/odk-workflows/ManageDocumentation.md
	modified:   ../../docs/odk-workflows/RepoManagement.md
	modified:   Makefile
	modified:   run.sh
	modified:   ../scripts/update_repo.sh
	modified:   ../sparql/class-count-by-prefix.sparql

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../scripts/run-command.sh
	../sparql/dc-properties-violation.sparql

**Comment by hoganwr** [comment]
Now the new check is failing:

FAIL Rule ../sparql/dc-properties-violation.sparql: 109 violation(s)

**Comment by matentzn** [comment]
You can customise the ODK checks like this 

https://github.com/obophenotype/human-phenotype-ontology/blob/2db36f33b844cbba651fae3374b69e9214b24fce/src/ontology/hp-odk.yaml#L159

I can fix it for you tomorrow if you want (just say the word before you close for today).

Of course the best would be to fix the problem (avoiding dc elements) but I understand you want to get this done now..

**Comment by jamesaoverton** [comment]
Ok, I committed the updated ODK files and fixed the dc-properties-violation problem.

**Comment by hoganwr** [comment]
Ok I made a fresh clone (too many local changes, and git stash wasn't working as a quick fix LOL) and started anew. I had to run update_repo again.

Thus far, I am past the point where I got the dc-properties-violation. So progress! From here the build takes many hours, so I'll report back either very late this evening or first thing in the morning.

**Comment by hoganwr** [comment]
Well, the build finished extremely quickly, and the reason is that dron-rxnorm.owl and dron-ndc.owl are empty. Going back to re-rerun make_components to see if there was a message I missed.

**Comment by hoganwr** [comment]
It seems that now the conversion from the ttl (that gets exported from ldtab) to owl is not happening at all. So although dron-rxnorm.ttl, dron-ndc.ttl, dron-ingredient.ttl, and dron-obsolete.ttl are all there and non-empty (and their sizes are in proportions you'd roughly expect), the owl files are all size 0 and empty.

**Comment by jamesaoverton** [comment]
Ok, I think I'm figuring this out.

The "INVALID FORMAT ERROR unknown format: owl" was caused when the Turtle contains a value like `"30 MG"^^xsd:double` which is not a valid number. I fixed that by editing `clinical_drug_strength.tsv`.

The failure to convert `.ttl` to `.owl` is because of a change in the ODK `Makefile` defining `$(COMPONENTSDIR)/%.owl`. I fixed that my making the Makefile tasks more specific.

**Comment by hoganwr** [comment]
For now can confirm that the make_components is successful and the owl files are there and sizes are expected. I'm now running the next step in the build and that will take hours.

Apologies for the bad DrOn design re: strengths. Getting this process working is so we can fix, update, correct, enhance, and extend the build to fix issues exactly like that...

Nico, thanks for the offer. I am not sure how we're using dc:elements but I'd be happy to get rid of it.

**Review by hoganwr — APPROVED** [review]
The build completed successfully and I spot checked the results in Protege. I also looked at the template files. All looks good!

**Comment by hoganwr** [comment]
Also, I can't merge this pull request at the moment. Is it looking for an additional review?

**Pull request merged**
