### PR TITLE
Release 2024-07-30

### PR DESCRIPTION
**Pull request by jamesaoverton**
- Updated labels from RxNorm 01022024 and latest ChEBI
- Obsolete 8 DrOn ingredients in favor of ChEBI terms
- Updated DrOn from RxNorm 01022024

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I updated DrOn from RxNorm 01022024. @hoganwr Can you please follow the `docs/DronReleaseWorkflow.md` to update for February, and let me know if you run into any problems?

**Review by hoganwr — APPROVED** [review]
Everything looks good. Built successfully. Protege spot check is good.

**Comment by hoganwr** [comment]
Oh sorry, I see I'm supposed to follow the whole thing to add Feb RxNorm to your updates, which include Jan.  Apologies. Will start that now!

**Comment by hoganwr** [comment]
Ok I successfully ran the update for 02052024 version of RxNorm. Note that to successfully push my changes here to GitHub from my local repo clone I had to git config http.postBuffer 524288000

**Comment by jamesaoverton** [comment]
Yes, your commits look good! Please try adding March, and then hopefully complete the release process.

**Comment by hoganwr** [comment]
Ran March through update-rxnorm. It only updated ingredient.tsv and rxcui.tsv.  There were no errors. Now I suppose it's possible that there really weren't other new things, although usually the new ingredient is in service of new SCDF, SCD, and possibly SBD. Can you run it too and see what you get?

**Comment by jamesaoverton** [comment]
Yes, good idea. I'll run February and March and compare.

**Comment by jamesaoverton** [comment]
My update for February matched yours exactly. But when I tried to update for March, the `tmp/rxnorm.db` stayed stuck on February. I committed two small changes to fix that, and now `git diff --stat` shows 2 new CDFs, 19 new CDs, 19 new BDs, 3 new ingredients, etc.

Please try again, starting from my commit, then fetching March, and continuing the workflow from there to see if you get the same numbers.

**Pull request merged**
