### PR TITLE
Fix problems with clinical drug strength units

### PR DESCRIPTION
**Pull request by jamesaoverton**
- Add unit table, update clinical_drug_strength
- Fix bad column name in report-problems
- Add IAO and UO imports
- Sort unit table

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I'll test a full build with this PR tonight, and PR #33 tomorrow.

**Review by hoganwr — APPROVED** [review]
I've reviewed all the new & updated templates and imports. Thanks for fixing the other imports besides UO as well :-). I then carried out a successful build and spot checked it in Protege. Ready to merge.

**Comment by hoganwr** [comment]
I'll wait for the outcome of your own testing of this PR before proceeding (sorry just saw your note about it).

**Comment by jamesaoverton** [comment]
My tests were successful, so I'll merge now.

**Pull request merged**
